-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-10-29 07:48:55 SGT
--   site:      DB2/UDB 7.1
--   type:      DB2/UDB 7.1



CREATE TABLE AKUN 
    (
     Username CHAR (5) NOT NULL , 
     Password VARCHAR (15) NOT NULL , 
     Nama VARCHAR (20) NOT NULL , 
     Gender VARCHAR (12) NOT NULL , 
     Jabatan VARCHAR (10) NOT NULL 
    )
;

ALTER TABLE AKUN ADD PRIMARY KEY (Username)
;

CREATE TABLE HADIR
(
   Absensi VARCHAR(8) NOT NULL,
   HADIR_ID INT NOT NULL AUTO_INCREMENT,
   PRIMARY KEY (HADIR_ID)
)
;

CREATE TABLE IZIN
(
   Lama_Izin VARCHAR(8) NOT NULL,
   IZIN_ID INT NOT NULL AUTO_INCREMENT,
   PRIMARY KEY (IZIN_ID)
)
;

CREATE TABLE JADWAL_SHIFT 
    (
     ID_Jadwal CHAR (3) NOT NULL , 
     Nama_Karyawan VARCHAR (20) NOT NULL , 
     Tanggal DATE , 
     Jam_Masuk TIME NOT NULL , 
     Jam_Keluar TIME NOT NULL , 
     AKUN_Username CHAR (5) NOT NULL 
    )
;

ALTER TABLE JADWAL_SHIFT ADD PRIMARY KEY (ID_Jadwal)
;

CREATE TABLE KARYAWAN 
    (
     Username CHAR (5) NOT NULL , 
     Posisi VARCHAR (15) NOT NULL 
    )
;

ALTER TABLE KARYAWAN ADD PRIMARY KEY (Username)
;

CREATE TABLE LAPORAN_KEHADIRAN 
    (
     ID_Laporan CHAR (3) NOT NULL , 
     Nama_Karyawan VARCHAR (20) NOT NULL , 
     Tanggal DATE NOT NULL , 
     Status_Kehadiran VARCHAR (20) NOT NULL , 
     AKUN_Username CHAR (5) NOT NULL , 
     HADIR_HADIR_ID INT , 
     IZIN_IZIN_ID INT , 
     TANPA_KETERANGAN_TANPA_KETERANGAN_ID INT 
    )
;

ALTER TABLE LAPORAN_KEHADIRAN 
    ADD CONSTRAINT Arc_1 CHECK ( 
        (  (HADIR_HADIR_ID IS NOT NULL) AND 
         (IZIN_IZIN_ID IS NULL)  AND 
         (TANPA_KETERANGAN_TANPA_KETERANGAN_ID IS NULL) ) OR 
        (  (IZIN_IZIN_ID IS NOT NULL) AND 
         (HADIR_HADIR_ID IS NULL)  AND 
         (TANPA_KETERANGAN_TANPA_KETERANGAN_ID IS NULL) ) OR 
        (  (TANPA_KETERANGAN_TANPA_KETERANGAN_ID IS NOT NULL) AND 
         (HADIR_HADIR_ID IS NULL)  AND 
         (IZIN_IZIN_ID IS NULL) )  ) 
;

ALTER TABLE LAPORAN_KEHADIRAN ADD PRIMARY KEY (ID_Laporan)
;

CREATE TABLE MANAGER 
    (
     Username CHAR (5) NOT NULL 
    )
;

ALTER TABLE MANAGER ADD PRIMARY KEY (Username)
;

CREATE TABLE TANPA_KETERANGAN 
(
  Pesan_Peringatan VARCHAR(200) NOT NULL, 
  TANPA_KETERANGAN_ID INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (TANPA_KETERANGAN_ID)
)
;

ALTER TABLE JADWAL_SHIFT
    ADD CONSTRAINT JADWAL_SHIFT_AKUN_FK FOREIGN KEY
    ( 
     AKUN_Username
    ) 
    REFERENCES AKUN 
    ( 
     Username
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE KARYAWAN
    ADD CONSTRAINT KARYAWAN_AKUN_FK FOREIGN KEY
    ( 
     Username
    ) 
    REFERENCES AKUN 
    ( 
     Username
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE LAPORAN_KEHADIRAN
    ADD CONSTRAINT LAPORAN_KEHADIRAN_AKUN_FK FOREIGN KEY
    ( 
     AKUN_Username
    ) 
    REFERENCES AKUN 
    ( 
     Username
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE LAPORAN_KEHADIRAN
    ADD CONSTRAINT LAPORAN_KEHADIRAN_HADIR_FK FOREIGN KEY
    ( 
     HADIR_HADIR_ID
    ) 
    REFERENCES HADIR 
    ( 
     HADIR_ID
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE LAPORAN_KEHADIRAN
    ADD CONSTRAINT LAPORAN_KEHADIRAN_IZIN_FK FOREIGN KEY
    ( 
     IZIN_IZIN_ID
    ) 
    REFERENCES IZIN 
    ( 
     IZIN_ID
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE LAPORAN_KEHADIRAN
    ADD CONSTRAINT LAPORAN_KEHADIRAN_TANPA_KETERANGAN_FK FOREIGN KEY
    ( 
     TANPA_KETERANGAN_TANPA_KETERANGAN_ID
    ) 
    REFERENCES TANPA_KETERANGAN 
    ( 
     TANPA_KETERANGAN_ID
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

ALTER TABLE MANAGER
    ADD CONSTRAINT MANAGER_AKUN_FK FOREIGN KEY
    ( 
     Username
    ) 
    REFERENCES AKUN 
    ( 
     Username
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
;

DELIMITER $$

CREATE TRIGGER FNM_LAPORAN_KEHADI 
BEFORE UPDATE ON LAPORAN_KEHADIRAN
FOR EACH ROW
BEGIN
  SIGNAL SQLSTATE '45000'
  SET MESSAGE_TEXT = 'Non Transferable FK constraint on table LAPORAN_KEHADIRAN is violated';
END;
$$

DELIMITER ;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE ALIAS                             0
-- CREATE BUFFERPOOL                        0
-- CREATE DATABASE                          0
-- CREATE DISTINCT TYPE                     0
-- CREATE INSTANCE                          0
-- CREATE NODE GROUP                        0
-- CREATE TABLESPACE                        0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
